# Generated by Django 3.2 on 2022-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaSuporte',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
                ('ordem_servico', models.IntegerField(blank=True, null=True, verbose_name='OS')),
                ('ocorrencia', models.IntegerField(blank=True, null=True, verbose_name='OC')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observacao')),
                ('status', models.CharField(choices=[('p', 'pendente'), ('c', 'concluido'), ('e', 'tratando')], max_length=1)),
                ('cidade', models.CharField(choices=[(1, 'Alvorada'), (2, 'Arroio Do Meio'), (3, 'Bento Gonçalves'), (4, 'Cachoeira do Sul'), (5, 'Cachoeirinha'), (6, 'Campo Bom'), (7, 'Candelaria'), (8, 'Canguçu'), (9, 'Canoas'), (10, 'Capela De Santana'), (11, 'Charqueadas'), (12, 'Chuí'), (13, 'Cruz Alta'), (14, 'Cuiabá'), (15, 'Cuiabá Fronteira'), (16, 'Dois Irmãos'), (17, 'Encantado'), (18, 'Encruzilhada do Sul'), (19, 'Espumoso'), (20, 'Estancia Velha'), (21, 'Esteio'), (22, 'Estrela'), (23, 'Gravatai'), (24, 'Guaiba'), (25, 'Harmonia'), (26, 'Horizontina'), (27, 'Ibirubá'), (28, 'Imbé'), (29, 'Irai'), (30, 'Lagoa Vermelha'), (31, 'Lajeado'), (32, 'Lindolfo Color'), (33, 'Mato Leitão'), (34, 'Montenegro'), (35, 'Não Me Toque'), (36, 'Nova Petrópolis'), (37, 'Nova Prata'), (38, 'Novo Hamburgo'), (39, 'Pantano Grande'), (40, 'Paraí'), (41, 'Parobé'), (42, 'Porto Alegre'), (43, 'Quarai'), (44, 'Rio Pardo'), (45, 'Santa Cruz'), (46, 'Santa Maria'), (47, 'Santa Vitória Do Palmar'), (48, 'São Francisco de Paula'), (49, 'São Leopoldo'), (50, 'São Sepé'), (51, 'Sapiranga'), (52, 'Sapucaia do Sul'), (53, 'Sobradinho'), (54, 'SSP'), (55, 'Tramandaí'), (56, 'Três Coroas'), (57, 'UNIMED'), (58, 'Vacaria'), (59, 'Venâncio Aires'), (60, 'Vera Cruz')], max_length=100)),
            ],
            options={
                'verbose_name': 'pendencia',
                'verbose_name_plural': 'pendencias',
            },
        ),
    ]
