# Generated by Django 3.2 on 2022-01-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0002_alter_pendenciasuporte_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='PID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
