# Generated by Django 3.2 on 2022-01-06 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0003_alter_pendenciasuporte_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciasuporte',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendenciasuporte',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
