# Generated by Django 3.2 on 2022-01-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0004_auto_20220105_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendenciasuporte',
            options={'ordering': ['criado_em'], 'verbose_name': 'pendencia', 'verbose_name_plural': 'pendencias'},
        ),
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
