# Generated by Django 3.2 on 2022-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0007_alter_pendenciasuporte_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='cidade',
            field=models.CharField(choices=[('DGT Base', 'DGT Base'), ('Alvorada', 'Alvorada'), ('Arroio Do Meio', 'Arroio Do Meio'), ('Bento Gonçalves', 'Bento Gonçalves'), ('Cachoeira do Sul', 'Cachoeira do Sul'), ('Cachoeirinha', 'Cachoeirinha'), ('Campo Bom', 'Campo Bom'), ('Candelaria', 'Candelaria'), ('Canguçu', 'Canguçu'), ('Canoas', 'Canoas'), ('Capela De Santana', 'Capela De Santana'), ('Charqueadas', 'Charqueadas'), ('Chuí', 'Chuí'), ('Cruz Alta', 'Cruz Alta'), ('Cuiabá', 'Cuiabá'), ('Cuiabá Fronteira', 'Cuiabá Fronteira'), ('Dois Irmãos', 'Dois Irmãos'), ('Encantado', 'Encantado'), ('Encruzilhada do Sul', 'Encruzilhada do Sul'), ('Espumoso', 'Espumoso'), ('Estancia Velha', 'Estancia Velha'), ('Esteio', 'Esteio'), ('Estrela', 'Estrela'), ('Gravatai', 'Gravatai'), ('Guaiba', 'Guaiba'), ('Harmonia', 'Harmonia'), ('Horizontina', 'Horizontina'), ('Ibirubá', 'Ibirubá'), ('Imbé', 'Imbé'), ('Irai', 'Irai'), ('Lagoa Vermelha', 'Lagoa Vermelha'), ('Lajeado', 'Lajeado'), ('Lindolfo Color', 'Lindolfo Color'), ('Mato Leitão', 'Mato Leitão'), ('Montenegro', 'Montenegro'), ('Não Me Toque', 'Não Me Toque'), ('Nova Petrópolis', 'Nova Petrópolis'), ('Nova Prata', 'Nova Prata'), ('Novo Hamburgo', 'Novo Hamburgo'), ('Pantano Grande', 'Pantano Grande'), ('Paraí', 'Paraí'), ('Parobé', 'Parobé'), ('Passo Fundo', 'Passo Fundo'), ('Porto Alegre', 'Porto Alegre'), ('Quarai', 'Quarai'), ('Rio Pardo', 'Rio Pardo'), ('Santa Cruz', 'Santa Cruz'), ('Santa Maria', 'Santa Maria'), ('Santa Vitória Do Palmar', 'Santa Vitória Do Palmar'), ('São Francisco de Paula', 'São Francisco de Paula'), ('São Leopoldo', 'São Leopoldo'), ('São Sepé', 'São Sepé'), ('Sapiranga', 'Sapiranga'), ('Sapucaia do Sul', 'Sapucaia do Sul'), ('Sobradinho', 'Sobradinho'), ('SSP', 'SSP'), ('Tramandaí', 'Tramandaí'), ('Três Coroas', 'Três Coroas'), ('UNIMED', 'UNIMED'), ('Vacaria', 'Vacaria'), ('Venâncio Aires', 'Venâncio Aires'), ('Vera Cruz', 'Vera Cruz')], max_length=100),
        ),
    ]
