# Generated by Django 3.2 on 2022-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0008_alter_pendenciasuporte_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='status',
            field=models.CharField(choices=[('p', 'pendente'), ('pt', 'pendente terceiro'), ('pc', 'pendente cliente'), ('c', 'concluido'), ('t', 'tratando')], max_length=2),
        ),
    ]
