# Generated by Django 3.2 on 2022-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0009_alter_pendenciasuporte_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='prioridade',
            field=models.CharField(choices=[('a', 'Alta'), ('m', 'Media'), ('b', 'Baixa')], max_length=1, null=True),
        ),
    ]
