# Generated by Django 3.2 on 2022-01-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0010_alter_pendenciasuporte_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='status',
            field=models.CharField(choices=[('pdgt', 'Pendente DGT'), ('ptp', 'Pendente Terceiro/Provedor'), ('pc', 'Pendente Cliente'), ('c', 'Concluido'), ('t', 'Tratando')], max_length=4),
        ),
    ]
