# Generated by Django 3.2 on 2022-01-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0012_pendenciasuporte_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendenciasuporte',
            options={'ordering': ['-criado_em'], 'verbose_name': 'pendencia', 'verbose_name_plural': 'pendencias'},
        ),
    ]
