# Generated by Django 3.2 on 2022-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0014_pendenciasuporte_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='imagem',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
