# Generated by Django 3.2 on 2022-01-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0015_alter_pendenciasuporte_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='observacao',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observacao'),
        ),
    ]
