# Generated by Django 3.2 on 2022-01-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0016_alter_pendenciasuporte_observacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendenciasuporte',
            old_name='author',
            new_name='usuario',
        ),
    ]
