# Generated by Django 3.2 on 2022-01-11 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendencias', '0017_rename_author_pendenciasuporte_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_pendenciasuporte_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
