# Generated by Django 3.2 on 2022-01-11 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendencias', '0018_alter_pendenciasuporte_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
