# Generated by Django 3.2 on 2022-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0019_alter_pendenciasuporte_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
