# Generated by Django 3.2 on 2022-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0020_alter_pendenciasuporte_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendenciasuporte',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pendenciasuporte',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('Davi', 'Davi Lobato'), ('Rua', 'Ruã Goncalves'), ('Eduardo', 'Eduardo Palini'), ('Tiago', 'Tiago Cerveira')], max_length=100, null=True),
        ),
    ]
