# Generated by Django 3.2 on 2022-01-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0021_auto_20220111_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='responsavel',
            field=models.CharField(choices=[('Davi', 'Davi Lobato'), ('Rua', 'Ruã Goncalves'), ('Eduardo', 'Eduardo Palini'), ('Tiago', 'Tiago Cerveira')], max_length=100, null=True),
        ),
    ]
