# Generated by Django 3.2 on 2022-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0023_alter_pendenciasuporte_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='responsavel',
            field=models.CharField(choices=[('Davi', 'Davi Lobato'), ('Eduardo', 'Eduardo Palini'), ('Rita', 'Rita dos Santos'), ('Rua', 'Ruã Gonçalves'), ('Tiago', 'Tiago Cerveira')], max_length=100, null=True),
        ),
    ]
