# Generated by Django 3.2 on 2022-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0024_alter_pendenciasuporte_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='pendenciasuporte',
            name='imagem',
        ),
    ]
