# Generated by Django 3.2 on 2022-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0025_auto_20220111_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
        migrations.AddField(
            model_name='pendenciasuporte',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
