# Generated by Django 3.2 on 2022-01-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendencias', '0027_alter_pendenciasuporte_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasuporte',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observacao'),
        ),
    ]
